### ISSUE TITLE
compute: missing resources

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/google-cloud-node#1073]
RE: #1071 

As it is today, we're missing the following resource types:
- [x] [Autoscalers](https://cloud.google.com/compute/docs/reference/latest/#Autoscalers) (@stephenplusplus) PR: #1137
- [x] [BackendServices](https://cloud.google.com/compute/docs/reference/latest/#BackendServices) (@stephenplusplus) PR: #1159
- [x] [ForwardingRules](https://cloud.google.com/compute/docs/reference/latest/#ForwardingRules) (@stephenplusplus) PR: #1191
- [x] [Http(s)HealthChecks](https://cloud.google.com/compute/docs/reference/latest/#HttpHealthChecks) (@stephenplusplus) PR: #1276
- [ ] [Images](https://cloud.google.com/compute/docs/reference/latest/#Images)
- [ ] [InstanceGroupManagers](https://cloud.google.com/compute/docs/reference/latest/#InstanceGroupManagers)
- [x] [InstanceGroups](https://cloud.google.com/compute/docs/reference/latest/#InstanceGroups) - #1071 (@stephenplusplus) PR: #1320
- [ ] [InstanceTemplates](https://cloud.google.com/compute/docs/reference/latest/#InstanceTemplates) - #1071 
- [ ] [Instances](https://cloud.google.com/compute/docs/reference/latest/#Instances)
- [ ] [Licenses](https://cloud.google.com/compute/docs/reference/latest/#Licenses)
- [x] [MachineTypes](https://cloud.google.com/compute/docs/reference/latest/#MachineTypes)
- [x] [Projects](https://cloud.google.com/compute/docs/reference/latest/#Projects) PR: #2506
- [ ] [Routes](https://cloud.google.com/compute/docs/reference/latest/#Routes)
- [ ] [SslCertificates](https://cloud.google.com/compute/docs/reference/latest/#SslCertificates)
- [x] [Subnetworks](https://cloud.google.com/compute/docs/reference/latest/#Subnetworks)
- [ ] [TargetHttp(s)Proxies](https://cloud.google.com/compute/docs/reference/latest/#SslCertificates)
- [ ] [TargetPools](https://cloud.google.com/compute/docs/reference/latest/#TargetPools)
- [ ] [TargetVpnGateways](https://cloud.google.com/compute/docs/reference/latest/#TargetVpnGateways)
- [ ] [UrlMaps](https://cloud.google.com/compute/docs/reference/latest/#UrlMaps)
- [ ] [VpnTunnels](https://cloud.google.com/compute/docs/reference/latest/#VpnTunnels)
## How can I help?

There's a basic structure in place for the source and test files: https://github.com/stephenplusplus/gcloud-node/tree/gce-template. It will probably be very helpful to check out the other Compute files to see our conventions and naming patterns. Send a PR as early as possible, so we can help with any questions along the way.
## I don't have time. I need these things now!

https://github.com/google/google-api-nodejs-client

**Comment by stephenplusplus** [comment]
I'm not sure if it's weird to only support *some* of the API, or if that's expected and matches our library's philosophy, which I think of as "make the common use case easy, don't bloat". @jgeewax hopefully can answer that.

If we only choose to support the common cases, our docs can suggest using the [full API client lib](https://github.com/google/google-api-nodejs-client) for the gaps.

If we do support all, I think a prioritization would be handy, then we can just go one-by-one, maybe even getting some help from the community.

**Comment by jtiden** [comment]
I'd like to help out, given there is a prioritization. My project needs over half of the listed missing resources.

**Comment by stephenplusplus** [comment]
Thanks! Feel free to claim any of the missing items listed above and I'll check it off.

I put a basic structure in place for the source and test files: https://github.com/stephenplusplus/gcloud-node/tree/gce-template. It will probably be very helpful to check out the other Compute files to see our conventions and naming patterns. Send a PR as early as possible, so @callmehiphop and I can help with any questions along the way.

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-compute#13
