### ISSUE TITLE
New x-goog-api-client information for gRPC-based APIs

### ISSUE THREAD

**Issue by jmuk** [GoogleCloudPlatform/google-cloud-node#2019]
(sorry not filed an issue so far); we are going to add x-goog-api-client header info to the gRPC-based APIs in certain format:
- common-grpc based: `"gl-node/(node version) gccl/(library version) grpc/(grpc version)"`
- APIs on top of gapic: `"gl-node/(node version) gccl/(library version) gapic/(autogen version) gax/(gax version) grpc/(grpc version)"`

Also the gapic autogen files will generate its own http header -- so that if the user chooses to use gapic layer directly, it has the information, but not with `gccl` part. This means we need to regenerate the autogen files too.

This issue tracks its progress.

The following APIs will be affected:
- [x] bigtable: common-grpc based (#2020)
- [x] datastore: common-grpc based (#2020)
- [x] language: on top of gapic (#2022)
- [x] language/gapic (#2022, #2037)
- [x] logging: common-grpc based (#2020)
- [x] logging/gapic (#2031)
- [x] monitoring/gapic (#2059)
- [x] pubsub: common-grpc based (#2020)
- [x] pubsub/gapic (#2032)
- [x] spanner: on top of gapic (#2066)
- [x] spanner/gapic (#2066)
- [x] speech: on top of gapic (#2025)
- [x] speech/gapic (#2025, #2037)
- [x] vision: on top of gapic (#2026)
- [x] vision/gapic (#2026, #2037)

**Comment by jmuk** [comment]
cc: @bjwatson @omaray @danoscarmike

**Comment by bjwatson** [comment]
Can we track the PRs for each API, the same way as we're doing for [Python](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3049) and [Ruby](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1268)?

**Comment by bjwatson** [comment]
@stephenplusplus @jmuk Can we track the PRs for each API, the same way as we're doing for [Python](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3049) and [Ruby](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1268)?

**Comment by bjwatson** [comment]
@jmuk Please note that this ordering is wrong:
> APIs on top of gapic: `"gl-node/(node version) gccl/(library version) gax/(gax version) gapic/(autogen version) grpc/(grpc version)"`

The `gapic/` token should appear before the `gax/` token:
> APIs on top of gapic: `"gl-node/(node version) gccl/(library version) gapic/(autogen version) gax/(gax version) grpc/(grpc version)"`

**Comment by jmuk** [comment]
My bad, it seems the ordering is different from both the expected order and what I wrote here, sigh. I'll make a fix for that.

**Comment by bjwatson** [comment]
Thanks, Jun.

**Comment by jmuk** [comment]
Now the code on master has this fully; @stephenplusplus or @callmehiphop -- please push new version of these API clients to npmjs.com, so that further API calls can contain this data.

**Comment by bjwatson** [comment]
Thanks @jmuk!

@stephenplusplus and @callmehiphop please let me know when all of the client libs have been republished with these new headers.

**Comment by stephenplusplus** [comment]
I'll be publishing these tomorrow. It involves a bit more work than expected because of a breaking change in `@google-cloud/common-grpc`.

**Comment by stephenplusplus** [comment]
All modules have been published.
